In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'name':['A','B','C','D','E'],
    'Department':['CS','IT','EC','CS','IT'],
})

In [3]:
df

  name Department
0    A         CS
1    B         IT
2    C         EC
3    D         CS
4    E         IT

In [4]:
df_encode = pd.get_dummies(df,columns=['Department'])
df_encode

  name  Department_CS  Department_EC  Department_IT
0    A           True          False          False
1    B          False          False           True
2    C          False           True          False
3    D           True          False          False
4    E          False          False           True

In [5]:
df_encode = pd.get_dummies(df,columns=['Department'],drop_first=True)
df_encode

  name  Department_EC  Department_IT
0    A          False          False
1    B          False           True
2    C           True          False
3    D          False          False
4    E          False           True

In [6]:
df_encode = pd.get_dummies(df,columns=['Department'],drop_first=True)
df_encode

  name  Department_EC  Department_IT
0    A          False          False
1    B          False           True
2    C           True          False
3    D          False          False
4    E          False           True

In [7]:
df = pd.DataFrame({
    'name':['A','B','C','D','E'],
    'Department':['CS','IT','EC','CS','IT'],
    'score':[60,45,78,90,34]
})
df['Grand']= np.where(df['score']>60,'A',np.where(df['score']>40,'B','C'))

In [8]:
df

  name Department  score Grand
0    A         CS     60     B
1    B         IT     45     B
2    C         EC     78     A
3    D         CS     90     A
4    E         IT     34     C

In [ ]:
pip install sklearn

In [1]:
from sklearn_model_selection import train_test_split
df = pd.DataFrame({
    'Hours':[1,2,3,4,5],
    'Score':[10,45,34,67,80],
    
})
x=df[['Hours']]
y=df[['Score']]

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size = 0.8)
print(x_train)
print(x_test)
# print(y_train)
# print(y_test)

ModuleNotFoundError: No module named 'sklearn_model_selection'