In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('StudentsPerformance.csv')

In [5]:
df.head()

   gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [7]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [8]:
df["math_pass"] = df["math score"].apply(lambda x: 1 if x >= 50 else 0)
df["reading_pass"] = df["reading score"].apply(lambda x: 1 if x >= 50 else 0)
df["writing_pass"] = df["writing score"].apply(lambda x: 1 if x >= 50 else 0)

In [10]:
df.head()

   gender race/ethnicity  ... reading_pass writing_pass
0  female        group B  ...            1            1
1  female        group C  ...            1            1
2  female        group B  ...            1            1
3    male        group A  ...            1            0
4    male        group C  ...            1            1

[5 rows x 11 columns]

In [11]:
df["Overall_Pass"] = df.apply(
    lambda row: 1 if row["math_pass"] == 1 and row["reading_pass"] == 1 and row["writing_pass"] == 1 else 0,
    axis=1
)

In [13]:
df.head()

   gender race/ethnicity  ... writing_pass Overall_Pass
0  female        group B  ...            1            1
1  female        group C  ...            1            1
2  female        group B  ...            1            1
3    male        group A  ...            0            0
4    male        group C  ...            1            1

[5 rows x 12 columns]

In [14]:
df.drop(["math score", "reading score", "writing score"], axis=1, inplace=True)

In [15]:
df.head()

   gender race/ethnicity  ... writing_pass Overall_Pass
0  female        group B  ...            1            1
1  female        group C  ...            1            1
2  female        group B  ...            1            1
3    male        group A  ...            0            0
4    male        group C  ...            1            1

[5 rows x 9 columns]

In [16]:
df = pd.get_dummies(df,drop_first=True)

In [18]:
df.head()

   math_pass  reading_pass  ...  lunch_standard  test preparation course_none
0          1             1  ...            True                          True
1          1             1  ...            True                         False
2          1             1  ...            True                          True
3          0             1  ...           False                          True
4          1             1  ...            True                          True

[5 rows x 16 columns]

In [21]:
df.isna().sum()

math_pass                                        0
reading_pass                                     0
writing_pass                                     0
Overall_Pass                                     0
gender_male                                      0
race/ethnicity_group B                           0
race/ethnicity_group C                           0
race/ethnicity_group D                           0
race/ethnicity_group E                           0
parental level of education_bachelor's degree    0
parental level of education_high school          0
parental level of education_master's degree      0
parental level of education_some college         0
parental level of education_some high school     0
lunch_standard                                   0
test preparation course_none                     0
dtype: int64

In [22]:
df = df.dropna()

In [24]:
df.isna().sum()

math_pass                                        0
reading_pass                                     0
writing_pass                                     0
Overall_Pass                                     0
gender_male                                      0
race/ethnicity_group B                           0
race/ethnicity_group C                           0
race/ethnicity_group D                           0
race/ethnicity_group E                           0
parental level of education_bachelor's degree    0
parental level of education_high school          0
parental level of education_master's degree      0
parental level of education_some college         0
parental level of education_some high school     0
lunch_standard                                   0
test preparation course_none                     0
dtype: int64

In [26]:
x = df.drop("math_pass", axis=1)
y = df["math_pass"]

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=10
)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score
import seaborn as sns

In [30]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=10)
model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=10)

In [33]:
y_pred = model.predict(x_test)
print(y_pred)
print("Accuracy:", accuracy_score(y_test, y_pred))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
Accuracy: 0.96

In [ ]:
knn = KNeighborsClassifier()