# Task-1

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('RealEstate.csv')

In [3]:
df

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [4]:
df.dtypes

No                                          int64
X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

In [5]:
df = df.drop('No',axis=1)

In [6]:
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [7]:
df.isna().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [8]:
y = df[['Y house price of unit area']]
y

     Y house price of unit area
0                          37.9
1                          42.2
2                          47.3
3                          54.8
4                          43.1
..                          ...
409                        15.4
410                        50.0
411                        40.6
412                        52.5
413                        63.9

[414 rows x 1 columns]

In [9]:
x = df.drop('Y house price of unit area',axis=1)

In [10]:
x

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2012.917,19.5,306.59470,9,24.98034,121.53951
2,2013.583,13.3,561.98450,5,24.98746,121.54391
3,2013.500,13.3,561.98450,5,24.98746,121.54391
4,2012.833,5.0,390.56840,5,24.97937,121.54245
...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381
410,2012.667,5.6,90.45606,9,24.97433,121.54310
411,2013.250,18.8,390.96960,7,24.97923,121.53986
412,2013.000,8.1,104.81010,5,24.96674,121.54067
413,2013.500,6.5,90.45606,9,24.97433,121.54310

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7,random_state=110)

In [12]:
print(x_test.shape,x_train.shape,y_test.shape,y_train.shape)

(290, 6) (124, 6) (290, 1) (124, 1)

In [13]:
model = LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred = model.predict(x_test)
y_pred.size

290

In [16]:
 # Find and print coefficient and mean squared error of the regression model.
model.coef_

array([[ 1.06067397e+01, -1.36190526e-01, -4.94982109e-03,
         1.13338051e+00,  7.53265320e+01,  4.68068147e+00]])

In [17]:
model.intercept_

array([-23762.87626807])

In [18]:
mean_squared_error(y_test,y_pred)

93.0711945187882

# Task_2

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [20]:
df = pd.read_csv('insurance.csv')

In [21]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [22]:
df['bmi'] = np.where(df['bmi']<=18.5,'Underweight',
        np.where(df['bmi']<=25,'Normal weight',
                np.where(df['bmi']<=30,'Over-weight','Obese')))

In [23]:
df
df.duplicated().sum()

np.int64(1)

In [24]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [25]:
df = pd.get_dummies(df,drop_first=True)
df

,age,children,charges,sex_male,bmi_Obese,bmi_Over-weight,bmi_Underweight,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,0,16884.92400,False,False,True,False,True,False,False,True
1,18,1,1725.55230,True,True,False,False,False,False,True,False
2,28,3,4449.46200,True,True,False,False,False,False,True,False
3,33,0,21984.47061,True,False,False,False,False,True,False,False
4,32,0,3866.85520,True,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,3,10600.54830,True,True,False,False,False,True,False,False
1334,18,0,2205.98080,False,True,False,False,False,False,False,False
1335,18,0,1629.83350,False,True,False,False,False,False,True,False
1336,21,0,2007.94500,False,False,True,False,False,False,False,True
1337,61,0,29141.36030,False,False,True,False,True,True,False,False

In [26]:
y = df[['charges']]

In [27]:
x = df.drop('charges',axis=1)

In [28]:
x

,age,children,sex_male,bmi_Obese,bmi_Over-weight,bmi_Underweight,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,0,False,False,True,False,True,False,False,True
1,18,1,True,True,False,False,False,False,True,False
2,28,3,True,True,False,False,False,False,True,False
3,33,0,True,False,False,False,False,True,False,False
4,32,0,True,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
1333,50,3,True,True,False,False,False,True,False,False
1334,18,0,False,True,False,False,False,False,False,False
1335,18,0,False,True,False,False,False,False,True,False
1336,21,0,False,False,True,False,False,False,False,True
1337,61,0,False,False,True,False,True,True,False,False

In [29]:
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1337 rows x 1 columns]

In [35]:
state = range(0,43)
mse_value = []
r2_value=[]

for i in state:
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=i)
    model = LinearRegression()
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    # prediction = pd.DataFrame({
    #     'Actual':y_test.squeeze(),
    #     'Predicted':y_pred.squeeze()
    # })

    mse = mean_squared_error(y_test,y_pred)
    r2 = r2_score(y_test,y_pred)

    mse_value.append(mse)
    r2_value.append(r2)

print("MSE Values: ",mse_value)
print("R2 Values: ",r2_value)
print('Random State: ', mse_value.index(min(mse_value)),'Min MSE: ',min(mse_value))
print('Random State: ', r2_value.index(max(r2_value)),'Max MSE: ',max(r2_value))

MSE Values:  [41099495.130760945, 30967924.929436114, 40930587.93682878, 34007287.67118918, 32553303.285415124, 39474193.72028926, 32524092.201694645, 41611773.023852445, 39614524.88974064, 36617511.34824024, 35372841.465823986, 23470348.801239345, 46844716.95742247, 32659979.972539667, 37901148.21552463, 30293186.039363213, 41446552.12719589, 29893185.69080647, 40042896.12227444, 40062568.76121305, 29965872.83941776, 33937233.25292569, 38216380.18202497, 39620868.108612485, 38201206.77354664, 34951221.71800944, 38443254.548775926, 35529076.42352903, 44314274.8041538, 49871102.318631224, 35895358.323213756, 35228805.06690622, 30406658.619724613, 34635628.29108292, 46118978.21588247, 35453928.22939199, 29316543.920726135, 37357648.64591674, 32720822.679207604, 45478409.210064925, 34714163.21521867, 31212392.731234208, 36733939.68129799]
R2 Values:  [0.7556939848877449, 0.76060631375011, 0.7290028733140816, 0.7695879092931386, 0.7407786609104581, 0.732797432772543, 0.7644605250706127, 0.7424009953178945, 0.7268016344862729, 0.7073312544235367, 0.7386806496621836, 0.8209772777310961, 0.7385967618035372, 0.7479376912230569, 0.6701288298127043, 0.794447901834916, 0.7320697956212193, 0.7562996094883995, 0.7226286393634509, 0.7499323514539511, 0.8004211899827963, 0.7222671193797356, 0.7607339249818413, 0.721753676984284, 0.7748220336375966, 0.7629250655036584, 0.7617698364759578, 0.7047180992836519, 0.7463224549305008, 0.7199896817711919, 0.749479276538663, 0.7375908810487619, 0.7942059551179342, 0.7479015844648831, 0.7203246918241312, 0.7574736226488109, 0.7479455523414533, 0.719877454395732, 0.7363514015440076, 0.7205153939408628, 0.7831632164535584, 0.7099272128367433, 0.8000940003096607]
Random State:  11 Min MSE:  23470348.801239345
Random State:  11 Max MSE:  0.8209772777310961

In [36]:
# After finding the best models, we predict the insurance charges for
# a new individual with specific given features (age 34, male, BMI 26, 3 children,
# smoker, southwest region).
x_test = [[34,True,False,True,False,3,True,False,False,True]]
new_y_pred = model.predict(x_test)
print(new_y_pred)

[[23994.69087302]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(